// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFileBase64(arg1) {
  return window['go']['app']['ExportAPI']['ExportFileBase64'](arg1);
}
