// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Delete(arg1:number):Promise<boolean>;

export function ListByProject(arg1:number):Promise<Array<domain.File>>;
