// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['app']['FileAPI']['Delete'](arg1);
}

export function ListByProject(arg1) {
  return window['go']['app']['FileAPI']['ListByProject'](arg1);
}
