// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ImportBase64(arg1:app.ImportRequest):Promise<app.ImportResponse>;

export function ParseBase64(arg1:app.ImportRequest):Promise<app.ParseResponse>;
