// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportBase64(arg1) {
  return window['go']['app']['ImportAPI']['ImportBase64'](arg1);
}

export function ParseBase64(arg1) {
  return window['go']['app']['ImportAPI']['ParseBase64'](arg1);
}
