// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Cancel(arg1:number):Promise<boolean>;

export function Delete(arg1:number):Promise<boolean>;

export function Get(arg1:number):Promise<app.JobDTO>;

export function Items(arg1:number):Promise<Array<app.JobItemDTO>>;

export function List(arg1:number):Promise<Array<app.JobDTO>>;

export function Logs(arg1:number,arg2:number):Promise<Array<app.JobLogDTO>>;

export function StartTranslateFile(arg1:app.StartTranslateFileRequest):Promise<app.StartJobResponse>;

export function StartTranslateUnit(arg1:app.StartTranslateUnitRequest):Promise<app.StartJobResponse>;
