// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['app']['JobsAPI']['Cancel'](arg1);
}

export function Delete(arg1) {
  return window['go']['app']['JobsAPI']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['JobsAPI']['Get'](arg1);
}

export function Items(arg1) {
  return window['go']['app']['JobsAPI']['Items'](arg1);
}

export function List(arg1) {
  return window['go']['app']['JobsAPI']['List'](arg1);
}

export function Logs(arg1, arg2) {
  return window['go']['app']['JobsAPI']['Logs'](arg1, arg2);
}

export function StartTranslateFile(arg1) {
  return window['go']['app']['JobsAPI']['StartTranslateFile'](arg1);
}

export function StartTranslateUnit(arg1) {
  return window['go']['app']['JobsAPI']['StartTranslateUnit'](arg1);
}
