// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddLocale(arg1:number,arg2:string):Promise<domain.ProjectLocale>;

export function Create(arg1:string,arg2:string):Promise<domain.Project>;

export function Delete(arg1:number):Promise<boolean>;

export function List():Promise<Array<domain.Project>>;

export function ListLocales(arg1:number):Promise<Array<domain.ProjectLocale>>;

export function Update(arg1:number,arg2:string,arg3:string):Promise<domain.Project>;
