// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocale(arg1, arg2) {
  return window['go']['app']['ProjectAPI']['AddLocale'](arg1, arg2);
}

export function Create(arg1, arg2) {
  return window['go']['app']['ProjectAPI']['Create'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['app']['ProjectAPI']['Delete'](arg1);
}

export function List() {
  return window['go']['app']['ProjectAPI']['List']();
}

export function ListLocales(arg1) {
  return window['go']['app']['ProjectAPI']['ListLocales'](arg1);
}

export function Update(arg1, arg2, arg3) {
  return window['go']['app']['ProjectAPI']['Update'](arg1, arg2, arg3);
}
