// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['app']['ProviderAPI']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['app']['ProviderAPI']['Delete'](arg1);
}

export function List() {
  return window['go']['app']['ProviderAPI']['List']();
}

export function ListModels(arg1) {
  return window['go']['app']['ProviderAPI']['ListModels'](arg1);
}

export function ListModelsPreview(arg1) {
  return window['go']['app']['ProviderAPI']['ListModelsPreview'](arg1);
}

export function Test(arg1) {
  return window['go']['app']['ProviderAPI']['Test'](arg1);
}

export function Update(arg1) {
  return window['go']['app']['ProviderAPI']['Update'](arg1);
}
