// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';

export function Create(arg1:domain.Provider):Promise<domain.Provider>;

export function Delete(arg1:number):Promise<boolean>;

export function List():Promise<Array<domain.Provider>>;

export function ListModels(arg1:number):Promise<Array<app.ModelInfo>>;

export function ListModelsPreview(arg1:domain.Provider):Promise<Array<app.ModelInfo>>;

export function Test(arg1:number):Promise<app.ProviderTestResult>;

export function Update(arg1:domain.Provider):Promise<domain.Provider>;
