// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ListUnitTexts(arg1:number,arg2:string):Promise<Array<app.UnitText>>;

export function Upsert(arg1:app.UpsertTranslationRequest):Promise<boolean>;
