// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListUnitTexts(arg1, arg2) {
  return window['go']['app']['TranslationsAPI']['ListUnitTexts'](arg1, arg2);
}

export function Upsert(arg1) {
  return window['go']['app']['TranslationsAPI']['Upsert'](arg1);
}
