// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListByFile(arg1) {
  return window['go']['app']['UnitAPI']['ListByFile'](arg1);
}
