// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';

export function ListByFile(arg1:number):Promise<Array<domain.Unit>>;

export function UpsertBatch(arg1:number,arg2:Array<app.UpsertItem>):Promise<number>;
